when:
  - event: push
    branch: main

steps:
  - name: Pull Quartz repo
    image: alpine/git
    commands:
      - git clone https://gitea.cluster.stevenchen.one/steven/Personal-Website-Quartz.git
  
  - name: Quartz generate and move
    image: node:24-bookworm-slim
    commands:
      - mv $CI_WORKSPACE/writeups/quartz/* Personal-Website-Quartz/content/
      - cd Personal-Website-Quartz
      - npm i
      - npx quartz build
      - mv public/* $CI_WORKSPACE/writeups/quartz/

  - name: Build NGINX and push to registry
    image: docker:24-dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://127.0.0.1:2375
      IMAGE: gitea.cluster.stevenchen.one/steven/Personal-Website
      REGISTRY_USERNAME:
        from_secret: REGISTRY_USERNAME
      REGISTRY_TOKEN:
        from_secret: REGISTRY_TOKEN
    commands:
      - dockerd-entrypoint.sh &
      - |
        while ! docker info >/dev/null 2>&1; do
          echo "Waiting for Docker daemon..."
          sleep 1
        done
      - echo "$REGISTRY_TOKEN" | docker login gitea.cluster.stevenchen.one -u "$REGISTRY_USERNAME" --password-stdin
      - docker build -t $IMAGE:$CI_COMMIT_SHA .
      - docker push $IMAGE:$CI_COMMIT_SHA

  - name: Update gitops repo
    image: alpine/git
    environment:
      GITEA_TOKEN:
        from_secret: GITEA_TOKEN
    commands:
      - git config --global user.name "woodpecker"
      - git config --global user.email "ci@gitea.cluster.stevenchen.one"

      - git clone -b personal-website https://$GITEA_TOKEN:x-oauth-basic@gitea.cluster.stevenchen.one/steven/Personal-Website-Quartz.git
      - cd Personal-Website-Quartz/apps/website

      - apk update
      - apk add yq
      - yq -i '.spec.template.spec.containers[0].image = "gitea.cluster.stevenchen.one/steven/Personal-Website:${CI_COMMIT_SHA}"' deployment.yaml

      - git commit -am "chore - update website image to ${CI_COMMIT_SHA}"
      - git push origin main
